version: '2.1'

services:
  localstack:
    container_name: company-tribe-project-localstack
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=s3
      - DEBUG=s3
  api:
    build: .
    ports:
      - "8080-8081:8080-8081"
    depends_on:
      - "localstack"
